# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Dodoo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
     pod 'R.swift'
     pod 'SwiftyJSON'
#     pod 'Material'
    # pod 'EZSwiftExtensions'
#     pod 'NVActivityIndicatorView'
     pod 'ObjectMapper', '~> 3.3'
     pod 'Alamofire'
     pod 'Kingfisher', '~> 4.0'
     pod 'SwiftMessages', '~> 5.0'
  #   pod 'SidebarOverlay'
  #   pod 'RealmSwift'
     pod 'FBSDKCoreKit'
     pod 'FBSDKLoginKit'
     pod 'GoogleAnalytics'
     pod 'GoogleSignIn'
#     pod 'GooglePlaces'
     pod 'GoogleMaps'
#     pod 'GooglePlacesSearchController'
     pod 'GooglePlacePicker'
     pod 'Cosmos', '~> 17.0'
#     pod 'RxSwift'
#     pod 'RxCocoa'
     pod 'razorpay-pod', '1.1.7'
#     pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git', :branch => 'swift5.1'
     pod 'Firebase/Core'
     pod 'Firebase/Messaging'
     pod 'CashfreePG', '~> 2.0.8'
     #pod 'GooglePlacesAutocomplete'
     
  # Pods for Dodoo

  target 'DodooTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DodooUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
              end
      end
  end
  
  target 'ServiceExtension' do
      pod 'Firebase/Messaging'
#      pod 'FBSDKCoreKit'
#      pod 'FBSDKLoginKit'
#
  end

end
#config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
